
export enum EventSignalType {
  OPERATION_CREATE = "OPERATION_CREATE",
  OPERATION_EDIT = "OPERATION_EDIT",
  OPERATION_DELETE = "OPERATION_DELETE",

  OPERATION_TYPE_CREATE = "OPERATION_TYPE_CREATE",
  OPERATION_TYPE_EDIT = "OPERATION_TYPE_EDIT",
  OPERATION_TYPE_DELETE = "OPERATION_TYPE_DELETE",

  OPERATION_TAG_CREATE = "OPERATION_TAG_CREATE",
  OPERATION_TAG_EDIT = "OPERATION_TAG_EDIT",
  OPERATION_TAG_DELETE = "OPERATION_TAG_DELETE",

  OPERATION_CLIENT_CREATE = "OPERATION_CLIENT_CREATE",
  OPERATION_CLIENT_EDIT = "OPERATION_CLIENT_EDIT",
  OPERATION_CLIENT_DELETE = "OPERATION_CLIENT_DELETE",

  PROJECT_ACCOUNT_CREATE = "PROJECT_ACCOUNT_CREATE",
  PROJECT_ACCOUNT_EDIT = "PROJECT_ACCOUNT_EDIT",
  PROJECT_ACCOUNT_DELETE = "PROJECT_ACCOUNT_DELETE",

  PROJECT_CREATE = "PROJECT_CREATE",
  PROJECT_EDIT = "PROJECT_EDIT",
  PROJECT_DELETE = "PROJECT_DELETE",

  EXCEL_EXPORT_PROCESS = 'EXCEL_EXPORT_PROCESS',
  EXCEL_EXPORT_READY = 'EXCEL_EXPORT_READY',
}